###
GET http://localhost:3000/api/usuario HTTP/1.1
###
GET http://localhost:3000/api/usuario/4 HTTP/1.1
###
POST http://localhost:3000/api/usuario HTTP/1.1
Content-Type: application/json

{
    "nombreCompleto" : "Juan Perez",
    "username" : "juanperez",
    "password" : "123456",
    "tipoUsuario": "cliente"
}